Remove Android SDK Build Tools version (27.0.3)
mozilla-mobile/android-permission-handler pull request #9
Opened 2019-03-19 18:26 UTC by kartikgits

#8 Latest SDK built tools are used always if preferred.
Just removed that line in app/build.gradle

2019-03-20 02:13 UTC, mTwTm approved these changes
LGTM!

2019-03-20 02:17 UTC, mTwTm requested changes
Oh actually, there's another 27.0.3 in `permissionhandler/build.gradle` can you remove that too and make sure there's no other similar situations?

2019-03-20 03:15 UTC, kartikgits commented
Will look that up.

2019-03-22 01:34 UTC, mTwTm approved these changes
LGTM

2019-03-22 01:34 UTC, merged